[workspace]
resolver = "2"

members = [
    "chess",
    "engine",
    "tools",
]

[profile.dev.package.chess]
opt-level = 3
[profile.release]
codegen-units = 1
lto = "fat"

[profile.dev.build-override]
opt-level = 3
[profile.release.build-override]
opt-level = 3
